[phases.setup]
nixPkgs = [
    "php82",
    "php82Extensions.intl",
    "php82Extensions.mysqli",
    "php82Extensions.pdo_mysql",
    "php82Extensions.mbstring",
    "php82Extensions.curl",
    "php82Extensions.gd",
    "php82Extensions.zip",
    "php82Extensions.xml",
    "php82Extensions.opcache"
]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader --ignore-platform-reqs"]

[start]
cmd = "php -S 0.0.0.0:${PORT:-8080} -t public"